"""Added is_deleted column in contact table

Revision ID: 57cb01027e81
Revises: 00469b7202f9
Create Date: 2024-07-14 03:15:29.374657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '57cb01027e81'
down_revision: Union[str, None] = '00469b7202f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.alter_column('contact', 'linkedId',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contact', 'linkedId',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('contact', 'is_deleted')
    # ### end Alembic commands ###
